name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Hello world job
        run: |
          echo "Hello, World!"
      - name: Output date
        run: |
          date
      - name: Output current directory
        run: |
          ls